// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedOn            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	UpdatedOn            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_on,json=updatedOn,proto3" json:"updated_on,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Post) GetCreatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *Post) GetUpdatedOn() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedOn
	}
	return nil
}

type GetPostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdatePostRequest struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Post                 *Post                 `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdatePostRequest) Reset()         { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()    {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *UpdatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostRequest.Unmarshal(m, b)
}
func (m *UpdatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostRequest.Merge(m, src)
}
func (m *UpdatePostRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePostRequest.Size(m)
}
func (m *UpdatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostRequest proto.InternalMessageInfo

func (m *UpdatePostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdatePostRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *UpdatePostRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type DeletePostRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRequest) Reset()         { *m = DeletePostRequest{} }
func (m *DeletePostRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePostRequest) ProtoMessage()    {}
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *DeletePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRequest.Unmarshal(m, b)
}
func (m *DeletePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRequest.Marshal(b, m, deterministic)
}
func (m *DeletePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRequest.Merge(m, src)
}
func (m *DeletePostRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePostRequest.Size(m)
}
func (m *DeletePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRequest proto.InternalMessageInfo

func (m *DeletePostRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListPostResponse struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostResponse) Reset()         { *m = ListPostResponse{} }
func (m *ListPostResponse) String() string { return proto.CompactTextString(m) }
func (*ListPostResponse) ProtoMessage()    {}
func (*ListPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *ListPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostResponse.Unmarshal(m, b)
}
func (m *ListPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostResponse.Marshal(b, m, deterministic)
}
func (m *ListPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostResponse.Merge(m, src)
}
func (m *ListPostResponse) XXX_Size() int {
	return xxx_messageInfo_ListPostResponse.Size(m)
}
func (m *ListPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostResponse proto.InternalMessageInfo

func (m *ListPostResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "service.post.v1.Post")
	proto.RegisterType((*GetPostRequest)(nil), "service.post.v1.GetPostRequest")
	proto.RegisterType((*UpdatePostRequest)(nil), "service.post.v1.UpdatePostRequest")
	proto.RegisterType((*DeletePostRequest)(nil), "service.post.v1.DeletePostRequest")
	proto.RegisterType((*ListPostResponse)(nil), "service.post.v1.ListPostResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x9d, 0x84, 0x36, 0x13, 0xd2, 0xa6, 0x83, 0x4a, 0x2d, 0x03, 0x6a, 0xf0, 0xa9, 0x2d,
	0xc8, 0x56, 0xd3, 0x13, 0x70, 0x40, 0x32, 0x5f, 0x17, 0x50, 0x90, 0x01, 0x09, 0x71, 0x89, 0x36,
	0xf1, 0xb6, 0x5a, 0xd5, 0xf1, 0x1a, 0xef, 0x26, 0x12, 0x42, 0x5c, 0x38, 0x72, 0xe5, 0xce, 0x9f,
	0x42, 0x82, 0x3f, 0xc0, 0xaf, 0xe8, 0x09, 0xed, 0x7a, 0xdd, 0x10, 0x3b, 0x11, 0xbd, 0x79, 0x77,
	0xde, 0x7b, 0x33, 0xf3, 0xde, 0x1a, 0xba, 0x82, 0xe6, 0x73, 0x36, 0xa1, 0x7e, 0x96, 0x73, 0xc9,
	0x71, 0xfb, 0xf2, 0xc8, 0x85, 0xf4, 0xe7, 0xc7, 0xee, 0xfe, 0x19, 0xe7, 0x67, 0x09, 0x0d, 0x74,
	0x79, 0x3c, 0x3b, 0x0d, 0x24, 0x9b, 0x52, 0x21, 0xc9, 0x34, 0x2b, 0x18, 0xee, 0xad, 0x2a, 0x80,
	0x4e, 0x33, 0xf9, 0xc9, 0x14, 0xf7, 0xe6, 0x24, 0x61, 0x31, 0x91, 0x34, 0x28, 0x3f, 0x4c, 0xe1,
	0xb6, 0x61, 0x91, 0x8c, 0x05, 0x24, 0x4d, 0xb9, 0x24, 0x92, 0xf1, 0x54, 0x98, 0x6a, 0xbf, 0xaa,
	0x79, 0xca, 0x68, 0x12, 0x8f, 0xa6, 0x44, 0x9c, 0x17, 0x08, 0xef, 0x97, 0x05, 0xcd, 0xd7, 0x5c,
	0x48, 0xdc, 0x02, 0x9b, 0xc5, 0x8e, 0xd5, 0xb7, 0x0e, 0xda, 0x91, 0xcd, 0x62, 0xbc, 0x03, 0x2d,
	0xc9, 0x64, 0x42, 0x1d, 0x5b, 0x5d, 0x85, 0x1b, 0x17, 0x61, 0x33, 0xb7, 0x7b, 0x76, 0x54, 0xdc,
	0xe2, 0x21, 0x74, 0x62, 0x2a, 0x26, 0x39, 0xcb, 0x54, 0x3f, 0xa7, 0xb1, 0x0c, 0xfa, 0xb7, 0x86,
	0x0f, 0x00, 0x26, 0x39, 0x25, 0x92, 0xc6, 0x23, 0x9e, 0x3a, 0xcd, 0xbe, 0x75, 0xd0, 0x19, 0xb8,
	0x7e, 0x31, 0x99, 0x5f, 0x4e, 0xe6, 0xbf, 0x2d, 0xed, 0x88, 0xda, 0x06, 0x3d, 0xd4, 0xd4, 0x59,
	0x16, 0x97, 0xd4, 0xd6, 0xff, 0xa9, 0x06, 0x3d, 0x4c, 0xbd, 0x43, 0xd8, 0x7a, 0x41, 0xa5, 0x5a,
	0x2d, 0xa2, 0x1f, 0x67, 0x54, 0x48, 0xdc, 0x5b, 0x6c, 0x58, 0x4e, 0x6a, 0xa9, 0x55, 0xbd, 0x1f,
	0x16, 0xec, 0xbc, 0xd3, 0xc4, 0xab, 0xc0, 0xf1, 0x04, 0x9a, 0x2a, 0x54, 0x6d, 0x4c, 0x67, 0xb0,
	0xeb, 0x57, 0x92, 0xf6, 0x95, 0x48, 0xb8, 0x79, 0x11, 0xb6, 0xbe, 0x59, 0x8a, 0xa2, 0xc1, 0xf8,
	0x08, 0x3a, 0xc5, 0x6c, 0xda, 0x7c, 0xed, 0xd7, 0xaa, 0x55, 0x9e, 0xab, 0x7c, 0x5e, 0x11, 0x71,
	0x1e, 0x99, 0xc5, 0xd5, 0xb7, 0x77, 0x1f, 0x76, 0x9e, 0xd2, 0x84, 0x5e, 0x6d, 0x3e, 0xef, 0x31,
	0xf4, 0x5e, 0x32, 0x61, 0x56, 0x17, 0x19, 0x4f, 0x05, 0xc5, 0x7b, 0xd0, 0x52, 0x63, 0x08, 0xc7,
	0xea, 0x37, 0xd6, 0x0e, 0x1d, 0x15, 0x98, 0xc1, 0xef, 0x06, 0x5c, 0x57, 0x67, 0xf1, 0xa6, 0x00,
	0xe1, 0x10, 0xe0, 0x89, 0xce, 0x44, 0xbf, 0x94, 0xd5, 0x64, 0x77, 0xf5, 0xb5, 0x77, 0xe3, 0xeb,
	0xcf, 0x3f, 0xdf, 0xed, 0xae, 0xb7, 0x19, 0xcc, 0x8f, 0x03, 0x55, 0x79, 0x68, 0x1d, 0xe1, 0x7b,
	0xd8, 0x30, 0xe1, 0xe0, 0x7e, 0x8d, 0xb6, 0x1c, 0xdb, 0x3a, 0xdd, 0x5d, 0xad, 0xbb, 0x8d, 0xdd,
	0x52, 0x37, 0xf8, 0xcc, 0xe2, 0x2f, 0x38, 0x02, 0x58, 0x58, 0x85, 0x5e, 0x8d, 0x5b, 0xf3, 0xd1,
	0xbd, 0x59, 0x0b, 0xe1, 0x99, 0xfa, 0xf1, 0xca, 0x06, 0x47, 0x95, 0x06, 0x04, 0x60, 0xf1, 0x56,
	0x56, 0x34, 0xa8, 0x3d, 0xa4, 0x75, 0x0b, 0x38, 0x5a, 0x1f, 0xdd, 0x65, 0xfd, 0xc2, 0x9d, 0x76,
	0x19, 0xa0, 0xc0, 0x35, 0xe3, 0xb9, 0x77, 0x6b, 0xaa, 0xd5, 0xd0, 0xbd, 0x9e, 0xee, 0x00, 0x78,
	0x69, 0x7d, 0xd8, 0xfc, 0x60, 0x67, 0xe3, 0xf1, 0x35, 0x2d, 0x75, 0xf2, 0x37, 0x00, 0x00, 0xff,
	0xff, 0xbf, 0xd2, 0x3f, 0xf6, 0xb3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsServiceClient interface {
	CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Post, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error)
	DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*Post, error)
	ListPosts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListPostResponse, error)
}

type postsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostsServiceClient(cc grpc.ClientConnInterface) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/service.post.v1.PostsService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/service.post.v1.PostsService/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) DeletePost(ctx context.Context, in *DeletePostRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/service.post.v1.PostsService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/service.post.v1.PostsService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) ListPosts(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListPostResponse, error) {
	out := new(ListPostResponse)
	err := c.cc.Invoke(ctx, "/service.post.v1.PostsService/ListPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
type PostsServiceServer interface {
	CreatePost(context.Context, *Post) (*Post, error)
	GetPost(context.Context, *GetPostRequest) (*Post, error)
	DeletePost(context.Context, *DeletePostRequest) (*empty.Empty, error)
	UpdatePost(context.Context, *UpdatePostRequest) (*Post, error)
	ListPosts(context.Context, *empty.Empty) (*ListPostResponse, error)
}

// UnimplementedPostsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostsServiceServer struct {
}

func (*UnimplementedPostsServiceServer) CreatePost(ctx context.Context, req *Post) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostsServiceServer) GetPost(ctx context.Context, req *GetPostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedPostsServiceServer) DeletePost(ctx context.Context, req *DeletePostRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedPostsServiceServer) UpdatePost(ctx context.Context, req *UpdatePostRequest) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedPostsServiceServer) ListPosts(ctx context.Context, req *empty.Empty) (*ListPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPosts not implemented")
}

func RegisterPostsServiceServer(s *grpc.Server, srv PostsServiceServer) {
	s.RegisterService(&_PostsService_serviceDesc, srv)
}

func _PostsService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.post.v1.PostsService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).CreatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.post.v1.PostsService/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.post.v1.PostsService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).DeletePost(ctx, req.(*DeletePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.post.v1.PostsService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.post.v1.PostsService/ListPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).ListPosts(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.post.v1.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostsService_CreatePost_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostsService_GetPost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostsService_DeletePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostsService_UpdatePost_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _PostsService_ListPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
